# Generated by Django 5.0.6 on 2024-05-23 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clubName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ExtraData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yel_cards', models.IntegerField()),
                ('red_cards', models.IntegerField()),
                ('shots_att', models.IntegerField()),
                ('on_target_att', models.IntegerField()),
                ('woodwork', models.IntegerField()),
                ('header_goals', models.IntegerField()),
                ('penalty_goals', models.IntegerField()),
                ('freekick_goals', models.IntegerField()),
                ('ibox_goals', models.IntegerField()),
                ('obox_goals', models.IntegerField()),
                ('fastbreak_goals', models.IntegerField()),
                ('offsides', models.IntegerField()),
                ('zero_goals', models.IntegerField()),
                ('conceded_goals', models.IntegerField()),
                ('saves', models.IntegerField()),
                ('blocks', models.IntegerField()),
                ('interceptions', models.IntegerField()),
                ('tackles', models.IntegerField()),
                ('last_man_tackles', models.IntegerField()),
                ('clearances', models.IntegerField()),
                ('own_goals', models.IntegerField()),
                ('penalties_conceded', models.IntegerField()),
                ('goals_from_penalties', models.IntegerField()),
                ('passes', models.IntegerField()),
                ('long_balls', models.IntegerField()),
                ('crosses', models.IntegerField()),
                ('corners', models.IntegerField()),
                ('touches', models.IntegerField()),
                ('penalties_saved', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='teamData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('goals', models.IntegerField()),
                ('teamName', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stats.clubname')),
            ],
        ),
    ]
