# Generated by Django 5.0.6 on 2024-05-23 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extradata',
            name='teamName',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stats.clubname'),
        ),
    ]
