# Generated by Django 5.0.6 on 2024-06-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelinks',
            name='image_link',
            field=models.CharField(max_length=255),
        ),
    ]
