# Generated by Django 5.0.6 on 2024-05-24 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_extradata_teamname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Season',
        ),
    ]
